add captions for 2022-06-09
strega-nil-ms/stl-video-transcripts pull request #11
Opened 2022-10-15 18:11 UTC by fsb4000

Fixes #4

I will watch again tomorrow and collect all places where I am unsure about correctness.

2022-10-16 13:30 UTC, fsb4000 commented
Could you watch these links for ~10 seconds each and check correctness?

00:11:48.506 --> 00:11:51.480
https://youtu.be/i2wzjRJjuKY?t=706

00:17:39.478 --> 00:17:42.334
https://youtu.be/i2wzjRJjuKY?t=1059

00:23:11.816 --> 00:23:13.676
https://youtu.be/i2wzjRJjuKY?t=1389

00:29:10.974 --> 00:29:13.628
https://youtu.be/i2wzjRJjuKY?t=1751

00:29:36.110 --> 00:29:39.734
https://youtu.be/i2wzjRJjuKY?t=1778

00:30:11.704 --> 00:30:13.768
https://youtu.be/i2wzjRJjuKY?t=1812

00:37:52.820 --> 00:37:57.529
https://youtu.be/i2wzjRJjuKY?t=2273

00:38:32.120 --> 00:38:33.410
https://youtu.be/i2wzjRJjuKY?t=2312

00:42:26.330 --> 00:42:28.605
https://youtu.be/i2wzjRJjuKY?t=2546

00:45:00.090 --> 00:45:00.388
https://youtu.be/i2wzjRJjuKY?t=2700

00:52:06.500 --> 00:52:09.140
https://youtu.be/i2wzjRJjuKY?t=3126

2022-10-18 18:13 UTC, strega-nil-ms requested changes
Got some minor comments, and I've marked what I heard in the video :)

Thanks so, so much
<img src="https://user-images.githubusercontent.com/83086508/196511107-a3cb2d32-2fc8-484e-84df-222a78147da1.png" width=150 alt="oh my god thank you so muchhhh" />

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +catch it up in 1206.
```suggestion
patch it up in 1206.
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +Find their own range types
```suggestion
They can define their own range types
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +if you don't want to.
```suggestion
if you don't want to.
&gt;&gt; Casey: Or user-defined range types.
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Stephan: Convert size to handle this.
```suggestion
Convert size to handle this.
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Casey: It is unfortunate
```suggestion
&gt;&gt; Casey: That's unfortunate... I hit y to make sure it was a permalink
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Stephan: yeah, the fork is not wide itself.
```suggestion
&gt;&gt; Stephan: yeah, the fork is not... the repo itself.
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Stephan: Yeah, Casey recommends just
```suggestion
Yeah, Casey recommends just
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +I like this if we don't have concepts
```suggestion
I like this. If we don't have concepts
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Nicole: That's very good point.
```suggestion
&gt;&gt; Nicole: That's a very good point.
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Nicole: they're my context is it takes having a lot?
```suggestion
&gt;&gt; Nicole: Never mind I take it back
&gt;&gt; Stephan: the context is hiding a lot
```

2022-10-18 18:13 UTC, strega-nil-ms commented on transcripts/2022/2022-06-09/edited.vtt
> +&gt;&gt; Casey: Or do we always define another one in
```suggestion
&gt;&gt; Casey: Or do we always define... I know there's one in
```

2022-10-19 15:29 UTC, strega-nil-ms commented
Thank you!

2022-10-19 15:30 UTC, merged