Transcript for [[nodiscard]] video cr
strega-nil-ms/stl-video-transcripts pull request #14
Opened 2022-11-03 21:03 UTC by zacklj89

Transcription for #9 👍 

I tried following the instructions best I could. Please let me know if I messed anything up!

2022-11-03 22:36 UTC, zacklj89 commented on transcripts/2022/2022-08-25/edited.vtt
> +r attributes in general, umm
or

2022-11-04 03:04 UTC, fsb4000 commented on transcripts/2022/2022-08-25/edited.vtt
> +NOTE recognizability:0.763
```suggestion
```

2022-11-04 08:05 UTC, AlexGuteniev requested changes

2022-11-04 08:05 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +It's going to terminate with J thread.
```suggestion
It's going to terminate. With jthread
```

2022-11-04 08:05 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +Do we mark J thread ctor as
```suggestion
Do we mark jthread ctor as
```

2022-11-04 08:05 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +thread and then do nothing with it.
```suggestion
01:10:34.660 --> 01:10:36.585
It is unusual to construct a jthread 

01:10:36.585 --> 01:10:38.609
and then do nothing with it.
```

2022-11-04 08:05 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +thread ctor as nodiscard ctor.
```suggestion
01:10:43.720 --> 01:10:46.933
jthread. OK, we did in fact mark jthread 

01:10:46.933 --> 01:10:48.150
ctor as nodiscard ctor.
```

2022-11-06 03:58 UTC, fsb4000 requested changes
Nicole changed my `<` and `>` to `&lt;` and `&gt;` so I think we need to replace them.

2022-11-06 03:58 UTC, fsb4000 commented on transcripts/2022/2022-08-25/edited.vtt
> +vector<int> two = {40, 50, 60}.
```suggestion
vector&lt;int&gt; two = {40, 50, 60}.
```

2022-11-06 03:58 UTC, fsb4000 commented on transcripts/2022/2022-08-25/edited.vtt
> +For a vector<int> iterator,
```suggestion
For a vector&lt;int&gt; iterator,
```

2022-11-09 21:18 UTC, strega-nil-ms commented
I've sent it off to Lisa :)

2022-11-09 21:18 UTC, merged

2022-11-09 21:25 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +So what we really wanted was operator&&.
`&amp;&amp;`

2022-11-09 21:25 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +the && will work properly where
`&amp;&amp;`

2022-11-09 21:25 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +&lt;, &gt;, &lt;=, &gt;= is rewritten to <=>.
escape

2022-11-09 21:25 UTC, AlexGuteniev commented on transcripts/2022/2022-08-25/edited.vtt
> +<=> are treated differently.
escape